version: 2
formats: all
build:
  image: stable
python:
  version: "3.8"
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
sphinx:
  builder: html
  configuration: docs/source/conf.py
