import glob
import pandas as pd
from unity_vision.consumers.solo.parser import Solo
import argparse

parser = argparse.ArgumentParser(description='Input data directories to convert to COCO.')
parser.add_argument('-datadir', metavar='datadir', type=str, help='directory containing dataset generated by perception package.')
args = parser.parse_args()
# args.datadir = r"C:\GitHub\unity-vision\examples\data\solo"
sequences = glob.glob(f"{args.datadir}/sequence.*")


solo = Solo(args.datadir, sensors=["unity.solo.RGBCamera"], start=0, end=sequences.__len__())
sensor = "unity.solo.RGBCamera"
print(next(solo)[sensor])

