name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --requirement requirements/docs.txt
          pip list
        shell: bash
      - name: Make Documentation
        working-directory: ./docs
        run: |
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
