---

name: Docker Build and Deploy STG
on:
  push:
    branches:
      - chore/docker-image-creation
    tags:
      - "v*"
jobs:
  extract_tag:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.tag_extract.outputs.version_tag }}
    steps:
      - id: tag_extract
        run: |
          tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          echo "tag $tag"
          echo "::set-output name=version_tag::${tag}"

  build_and_deploy_docker_image:
    needs: [ extract_tag ]
    uses: ./.github/workflows/build-docker-image.workflow.yml
    with:
      tag: ${{ needs.extract_tag.outputs.version_tag }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_STG }}
      GCP_PROJECT: unity-ai-antojito-stg
