---

name: Publish to pypi

on:
  push:
    branches:
      - chore/public-pypi
  pull_request:
    branches:
      - chore/public-pypi

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
