name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --requirement requirements/docs.txt
          pip install -r requirements.txt
        shell: bash
#      - name: Build HTML
#        uses: ammaraskar/sphinx-action@master
#        with:
#          docs-folder: "docs/"
      - name: Make Documentation
        working-directory: docs
        run: |
          make html
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/build/html
#
#

#      - name: Make Documentation
#        working-directory: docs
#        run: |
#          make github
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#          publish_dir: docs/
